import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next and says so in its own header; it
  // is not ours to satisfy.
  { ignores: [".next/**", "node_modules/**", "e2e/**", "next-env.d.ts"] },
];
