"""job webhook_url

Revision ID: fd79c1bbd68b
Revises: 6b661963fe8e
Create Date: 2026-09-20 09:42:54.912316
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fd79c1bbd68b'
down_revision = '6b661963fe8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('webhook_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'webhook_url')
    # ### end Alembic commands ###
